update configure and gtkcompat.hxy

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,13 +3,20 @@
 # For more information, please refer to <http://unlicense.org/>
 #
 
+if ! [ -f Makefile ] ; then
+	echo 'Main Makefile is missing, cannot continue'
+	exit 1
+fi
+
 if ! cd $(dirname "$0") ; then
 	exit 1
 fi
 
 apps_to_check=''
 extra_env_vars=''
+make_extra_flags='' # config_mk_extra
 config_h_extra=''
+config_sh_extra=''
 extra_configure_opts=''
 config_h_have=
 config_mk_flags=
@@ -35,21 +42,37 @@ PACKAGE_VERSION="${VERSION}"
 # ./configure release [xz|gz|lz|bz2|zst]
 
 if [ "$1" = "release" ] ; then
-	if command -v git >/dev/null; then
-		printf "Run 'git clean -dfx'? [y/N]: "
-		read anzwer
-		case $anzwer in y|Y)
-			echo '# git clean -dfx'
-			git clean -dfx ;;
-		esac
-	fi
-	dir=${PACKAGE}-${VERSION}
-	rm -rf ../${dir}
-	mkdir -p ../${dir}
-	cp -rf $(pwd)/* ../${dir}
+	srcdir=$(pwd)
+	outdir=${PACKAGE}-${VERSION}
 	cd ..
-	echo "# tar -vcf ${dir}.tar $dir"
-	tar -vcf ${dir}.tar $dir
+	rm -rf ${outdir}
+	if [ "$2" = "dist" ] ; then
+		# force creation of tarfile, copy the whole dir
+		shift
+		shift
+		cp -rf ${srcdir} ${outdir}
+		cd ${outdir}
+		git clean -dfx
+		rm -rf .*
+		cd ..
+	else
+		if command -v git >/dev/null; then
+			printf "Run 'git clean -dfx'? [y/N]: "
+			read anzwer
+			case $anzwer in y|Y)
+				cd ${srcdir}
+				echo '# git clean -dfx'
+				git clean -dfx
+				cd ..
+				;;
+			esac
+		fi
+		mkdir -p ${outdir}
+		cp -rf ${srcdir}/* ${outdir}/
+	fi
+	#--
+	echo "# tar -vcf ${outdir}.tar ${outdir}"
+	tar -vcf ${outdir}.tar ${outdir}
 	comp=$2
 	if [ -z "$comp" ] ; then
 		comp=xz
@@ -61,16 +84,16 @@ if [ "$1" = "release" ] ; then
 		zst) cmd=zstd    ;;
 		*)   cmd=${comp} ;;
 	esac
-	rm -f ${dir}.tar.${comp}
-	echo "# ${cmd} ${dir}.tar"
-	if ${cmd} ${dir}.tar ; then
-		echo "*** ${dir}.tar.${comp} has been created..."
+	rm -f ${outdir}.tar.${comp}
+	echo "# ${cmd} ${outdir}.tar"
+	if ${cmd} ${outdir}.tar ; then
+		echo "*** ${outdir}.tar.${comp} has been created..."
 	fi
-	rm -f ${dir}.tar
+	rm -f ${outdir}.tar
 	exit
 fi
 
-# w_conf/gettext: ./configure po|pot|po2c
+# w_conf/gettext: ./configure po|pot
 
 #==========================================================
 
@@ -281,7 +304,10 @@ w_check_header_and_libs() # 1:<header> 2-:[libs] is optional
 	else
 		printf "Checking for ${xheaderx}... "
 	fi
-	ccode="#include <${xheaderx}>
+	ccode="#include <stdio.h>
+#include <stdlib.h>
+#include <inttypes.h>
+#include <${xheaderx}>
 int main (int argc, char **argv) { return 0; }
 "
 	w_compile_c_code "$ccode" "" "${xlibsx}"
@@ -332,6 +358,22 @@ w_check_headers_required()
 	done
 }
 
+
+w_check_cflag()
+{
+	printf "Checking if $1 is supported... "
+	c_code='int main (int argc, char **argv) { return 0; }'
+	w_compile_c_code "$ccode" ${1}
+	if [ $? -eq 0 ] ; then
+		echo "yes"
+		return 0
+	else
+		echo "no"
+		return 1
+	fi
+}
+
+
 w_check_command() # sets $wtmp_cmd
 {
 	printf "Checking for $1... "
@@ -378,23 +420,31 @@ w_check_command_find_first() # sets $wtmp_cmd
 }
 
 
-w_require_gnu_make()
+w_prefer_gnu_make() # param: require
 {
 	printf "Checking for GNU make... "
 	if [ -n "$MAKE" ] && "$MAKE" --version 1>/dev/null 2>&1 ; then
 		echo "$MAKE (environment)"
-		W_GNU_MAKE="MAKE = $MAKE"
+		W_GNU_MAKE="MAKE=$MAKE"
 	elif make --version 1>/dev/null 2>&1 ; then
 		echo "make"
-		W_GNU_MAKE='MAKE = make'
+		W_GNU_MAKE='MAKE=make'
 	elif gmake --version 1>/dev/null 2>&1 ; then
 		echo "gmake"
-		W_GNU_MAKE='MAKE = gmake'
+		W_GNU_MAKE='MAKE=gmake'
 	else
 		echo "no"
-		exit_error "ERROR: GNU make is required"
+		if [ -n "$1" ] ; then
+			exit_error "ERROR: GNU make is required"
+		fi
 	fi
 }
+
+w_require_gnu_make()
+{
+	w_prefer_gnu_make require
+}
+
 
 #==========================================================
 
@@ -578,7 +628,6 @@ do
 		--sbindir=*)    sbindir="$(getvalue $i)"    ;;
 		--libexecdir=*) libexecdir="$(getvalue $i)" ;;
 		--includedir=*) includedi="$(getvalue $i)"  ;;
-		--oldincludedir=*)  oldincludedi="$(getvalue $i)" ;;
 		--datarootdir=*)   datarootdir="$(getvalue $i)"   ;;
 		--datadir=*)    datadir="$(getvalue $i)"          ;;
 		--localstatedir=*) localstatedir="$(getvalue $i)" ;;
@@ -759,46 +808,16 @@ do
 done
 
 #==========================================================
-#             config.mk and Makefiles
+#                  config.mk
 #==========================================================
 
 # ensure -DHAVE_CONFIG_H
-CFLAGS="$CFLAGS -DHAVE_CONFIG_H"
-CXXFLAGS="$CXXFLAGS -DHAVE_CONFIG_H"
+CFLAGS="-DHAVE_CONFIG_H $CFLAGS "
+CXXFLAGS="-DHAVE_CONFIG_H $CXXFLAGS"
 
-if [ -z "$W_MAKEFILES_IN" ] ; then
-	w_makefiles=
-else
-	w_makefiles=$(find . -name Makefile.in | sed -e 's%.in%%')
-fi
-
-for makefile in config.mk ${w_makefiles}
-do
-	cat > ${makefile} <<EOF
+cat > config.mk <<EOF
 # generated by ./configure
 ${W_GNU_MAKE}
-CC = ${CC}
-CXX = ${CXX}
-STRIP = ${STRIP}
-AR = ${AR}
-AS = ${AS}
-NM = ${NM}
-RANLIB  = ${RANLIB}
-OBJCOPY = ${OBJCOPY}
-OBJDUMP = ${OBJDUMP}
-
-DLLTOOL = ${DLLTOOL}
-WINDRES = ${WINDRES}
-WINDMC  = ${WINDMC}
-
-CFLAGS = ${CFLAGS}
-CPPFLAGS = ${CPPFLAGS}
-CXXFLAGS = ${CXXFLAGS}
-LXXFLAGS = ${LXXFLAGS}
-LDFLAGS = ${LDFLAGS}
-LIBS = ${LIBS}
-
-#=================================================
 
 prefix = ${prefix}
 exec_prefix = ${exec_prefix}
@@ -807,7 +826,6 @@ bindir = ${bindir}
 sbindir = ${sbindir}
 libexecdir = ${libexecdir}
 includedir = ${includedir}
-oldincludedir = ${oldincludedir}
 datarootdir = ${datarootdir}
 datadir = ${datadir}
 localstatedir = ${localstatedir}
@@ -821,6 +839,8 @@ top_builddir = ${top_builddir}
 top_srcdir = ${top_srcdir}
 builddir = ${builddir}
 srcdir = ${srcdir}
+
+#=================================================
 
 INSTALL = install -c
 INSTALL_DATA = install -c -m 644
@@ -839,29 +859,142 @@ OS_CROSS = ${OS_CROSS}
 OS_TARGET = ${OS_TARGET}
 
 #=================================================
+
+CC = ${CC}
+CXX = ${CXX}
+STRIP = ${STRIP}
+AR = ${AR}
+AS = ${AS}
+NM = ${NM}
+RANLIB = ${RANLIB}
+OBJCOPY = ${OBJCOPY}
+OBJDUMP = ${OBJDUMP}
+
+DLLTOOL = ${DLLTOOL}
+WINDRES = ${WINDRES}
+WINDMC = ${WINDMC}
+
+CFLAGS = ${CFLAGS}
+CPPFLAGS = ${CPPFLAGS}
+CXXFLAGS = ${CXXFLAGS}
+LXXFLAGS = ${LXXFLAGS}
+LDFLAGS = ${LDFLAGS}
+LIBS = ${LIBS}
+
+#=================================================
 ${make_extra_flags}
-
+${w_config_mk_extra_lines}
 EOF
-	if [ -n "${config_mk_flags}" ] ; then
-		(
-			for env in ${config_mk_flags}
-			do
-				echo "${env}_CFLAGS = $(eval echo \$${env}_CFLAGS)"
-				echo "${env}_LIBS   = $(eval echo \$${env}_LIBS)"
-			done
-		) >> ${makefile}
-	fi
 
-	if [ -n "${w_config_mk_extra_lines}" ] ; then
-		echo "${w_config_mk_extra_lines}" >> ${makefile}
-	fi
+if [ -n "${config_mk_flags}" ] ; then
+	(
+		for env in ${config_mk_flags}
+		do
+			echo "${env}_CFLAGS = $(eval echo \$${env}_CFLAGS)
+${env}_LIBS  = $(eval echo \$${env}_LIBS)"
+		done
+	) >> config.mk
+fi
 
-	if [ -f ${makefile}.in ] ; then
-		cat ${makefile}.in >> ${makefile}
-	fi
+#==========================================================
+#                  config.sh (=config.mk)
+#==========================================================
 
-done
+cat > config.sh <<EOF
+#generated by ./configure
 
+prefix="${prefix}"
+exec_prefix="${exec_prefix}"
+libdir="${libdir}"
+bindir="${bindir}"
+sbindir="${sbindir}"
+libexecdir="${libexecdir}"
+includedir="${includedir}"
+datarootdir="${datarootdir}"
+datadir="${datadir}"
+localstatedir="${localstatedir}"
+sysconfdir="${sysconfdir}"
+docdir="${docdir}"
+infodir="${infodir}"
+mandir="${mandir}"
+localedir="${localedir}"
+runstatedir="${runstatedir}"
+top_builddir="${top_builddir}"
+top_srcdir="${top_srcdir}"
+builddir="${builddir}"
+srcdir="${srcdir}"
+
+#=================================================
+
+INSTALL="install -c"
+INSTALL_DATA="install -c -m 644"
+
+PACKAGE="${PACKAGE}"
+VERSION="${VERSION}"
+PACKAGE_URL="${PACKAGE_URL}"
+PACKAGE_NAME="${PACKAGE_NAME}"
+PACKAGE_STRING="${PACKAGE_STRING}"
+PACKAGE_TARNAME="${PACKAGE_TARNAME}"
+PACKAGE_BUGREPORT="${PACKAGE_BUGREPORT}"
+PACKAGE_VERSION="${PACKAGE_VERSION}"
+
+OS_BUILD="${OS_BUILD}"
+OS_CROSS="${OS_CROSS}"
+OS_TARGET="${OS_TARGET}"
+
+#=================================================
+
+CC="${CC}"
+CXX="${CXX}"
+STRIP="${STRIP}"
+AR="${AR}"
+AS="${AS}"
+NM="${NM}"
+RANLIB="${RANLIB}"
+OBJCOPY="${OBJCOPY}"
+OBJDUMP="${OBJDUMP}"
+
+DLLTOOL="${DLLTOOL}"
+WINDRES="${WINDRES}"
+WINDMC="${WINDMC}"
+
+CFLAGS="${CFLAGS}"
+CPPFLAGS="${CPPFLAGS}"
+CXXFLAGS="${CXXFLAGS}"
+LXXFLAGS="${LXXFLAGS}"
+LDFLAGS="${LDFLAGS}"
+LIBS="${LIBS}"
+
+#=================================================
+${config_sh_extra}
+EOF
+
+if [ -n "${config_mk_flags}" ] ; then
+	(
+		for env in ${config_mk_flags}
+		do
+			echo "${env}_CFLAGS=\"$(eval echo \$${env}_CFLAGS)\"
+${env}_LIBS=\"$(eval echo \$${env}_LIBS)\""
+		done
+	) >> config.sh
+fi
+
+
+#==========================================================
+#                  Makefiles.in
+#==========================================================
+
+if [ -n "$W_MAKEFILES_IN" ] ; then
+	w_makefiles=$(find . -name Makefile.in | sed -e 's%\.in%%')
+	for makefile in ${w_makefiles}
+	do
+		cat config.mk ${makefile}.in > ${makefile}
+	done
+fi
+
+#==========================================================
+
+. ./config.sh
 
 #==========================================================
 #                       config.h
@@ -881,11 +1014,11 @@ cat > config.h <<EOF
 #define PACKAGE_BUGREPORT "${PACKAGE_BUGREPORT}"
 #define PACKAGE_VERSION "${PACKAGE_VERSION}"
 
-#define PREFIX "$(print_eval_var $prefix)"
-#define DOCDIR "$(print_eval_var $docdir)"
-#define LOCALEDIR "$(print_eval_var $localedir)"
-#define DATADIR "$(print_eval_var $datadir)"
-#define SYSCONFDIR "$(print_eval_var $sysconfdir)"
+#define PREFIX "$prefix"
+#define DOCDIR "$docdir"
+#define LOCALEDIR "$localedir"
+#define DATADIR "$datadir"
+#define SYSCONFDIR "$sysconfdir"
 
 #define OS_TARGET "${OS_TARGET}"
 ${config_h_extra}
@@ -913,22 +1046,14 @@ fi
 echo "${w_config_h_extra_lines}
 #endif /* __W_CONFIGURE_CONFIG_H__ */" >> config.h
 
-#============================================================
+#==========================================================
 
 for infile in ${w_infiles}
 do
-	if [ -f ${infile}.in ] ; then
-		sed -e "s%@VERSION@%${VERSION}%g" \
-			-e "s%@PACKAGE@%${PACKAGE}%g" \
-			-e "s%@PACKAGE_URL@%${PACKAGE_URL}%g" \
-			${infile}.in > ${infile}
-	else
-		echo "WARNING: ${infile}.in doesn't exist"
-		printf "" > ${infile}
-	fi
+	./w_conf/00_standard_infile.sh ${infile}
 done
 
-#============================================================
+#==========================================================
 
 echo
 echo "* Now run 'make'  (or 'make clean' first if the app is already compiled)"
